template:
  templates:
    - { template-id: "001", template-file-path: "kafka-01/src/main/resources/template/template.json", active: true }
    - { template-id: "002", template-file-path: "kafka-01/src/main/resources/template/template.json", active: false }
  template-result-type: 0
  template-result-file-path: "kafka-01/src/main/resources/template/templateResult.json"

#logging:
#  config: classpath:logback.xml